#!/bin/sh
#
# @name HEAR quad ethernet indoor
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Abdulla Ayyad <abdulla.ayyad96@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default IMU_GYRO_CUTOFF 30

param set-default CA_ROTOR_COUNT 4

param set-default IMU_INTEG_RATE 400
param set-default EKF2_PREDICT_US 2500

param set-default EKF2_HGT_REF 3
param set-default EKF2_GPS_CTRL 0
param set-default EKF2_BARO_CTRL 0
param set-default EKF2_RNG_CTRL 0
param set-default EKF2_MAG_TYPE 5
param set-default EKF2_EV_TYPE 15

param set-default COM_DISARM_PRFLT 1000.00

param set-default COM_DISARM_LAND  -1.0
param set-default MPC_THR_HOVER  0.25

param set-default SYS_HAS_MAG  0

param set-default COM_OBL_RC_ACT 7

param set-default MAV_1_CONFIG 102
param set-default MAV_1_FLOW_CTRL 2
param set-default MAV_1_FORWARD 0
param set-default MAV_1_MODE 1
param set-default MAV_1_RADIO_CTL 1
param set-default MAV_1_RATE  1000000
param set-default MAV_2_CONFIG 0

param set-default SER_TEL2_BAUD 921600


control_allocator stop


