#!/bin/sh
#
# @name HEAR quad ethernet indoor
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Abdulla Ayyad <abdulla.ayyad96@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default IMU_GYRO_CUTOFF 30

param set-default CA_ROTOR_COUNT 4

param set-default IMU_INTEG_RATE 400
param set-default EKF2_PREDICT_US 2500

param set-default EKF2_HGT_REF 0
param set-default EKF2_GPS_CTRL 7
param set-default EKF2_BARO_CTRL 1
param set-default EKF2_RNG_CTRL 0
param set-default EKF2_MAG_TYPE 2
param set-default EKF2_EV_TYPE 0

param set-default COM_DISARM_PRFLT 1000.00

param set-default COM_DISARM_LAND  -1.0
param set-default MPC_THR_HOVER  0.25

param set-default SYS_HAS_MAG  1

param set-default COM_OBL_RC_ACT 7

param set-default MAV_2_CONFIG 1000
param set-default MAV_2_FLOW_CTRL 2
param set-default MAV_2_FORWARD 0
param set-default MAV_2_RATE  2000000
param set-default MAV_2_BROADCAST  1
param set-default MAV_2_RADIO_CTL 0
param set-default MAV_2_REMOTE_PRT  14540
param set-default MAV_2_UDP_PRT  14540
param set-default MAV_2_MODE 1

echo DEVICE=eth0 > /fs/microsd/net.cfg
echo BOOTPROTO=static >> /fs/microsd/net.cfg
echo IPADDR=192.168.144.4 >> /fs/microsd/net.cfg
echo NETMASK=255.255.255.0 >>/fs/microsd/net.cfg
echo ROUTER=192.168.144.1 >>/fs/microsd/net.cfg
echo DNS=192.168.144.1 >>/fs/microsd/net.cfg

control_allocator stop

param set-default MAV_0_CONFIG 101
param set-default MAV_0_FLOW_CTRL 2
param set-default MAV_0_FORWARD 0
param set-default MAV_0_MODE 0
param set-default MAV_0_RADIO_CTL 1
param set-default MAV_0_RATE  1000000

param set-default SER_TEL1_BAUD 57600

# Disable internal magnetometer and only use external mag
param set-default CAL_MAG0_PRIO 0

# Parameters for f9p / f8p GPS
param set-default SER_GPS1_BAUD 0
param set-default GPS_1_PROTOCOL 1

